def red2(): return "#FF0000"
def red3():
def red4():
def red5():
def red6():
def red7():
def red8():
def blue1():
def blue2():
def blue3():
def blue4():
def blue5():
def blue6():
def blue7():
def blue8():
def green1():
def green2():
def green3():
def green4():
def green5():
def green6():
def green7():
def green8():
def yellow1():
def yellow2():
def yellow3():
def yellow4():
def yellow5():
def yellow6():
def yellow7():
def yellow8():
def purple1():
def purple2():
def purple3():
def purple4():
def purple5():
def purple6():
def purple7():
def purple8():
def orange1():
def orange2():
def orange3():
def orange4():
def orange5():
def orange6():
def orange7():
def orange8():
def pink1():
def pink2():
def pink3():
def pink4():
def pink4():
def pink5():
def pink6():
def pink7():
def pink8():
def turquoise1():
def turquoise2():
def turquoise3():
def turquoise4():
def turquoise5():
def turquoise6():
def turquoise7():
def turquoise8():